### PR TITLE
Removed a hidden button that routes to the "Guide Me" URL

### PR DESCRIPTION
**Pull request by jennifershinshin**
Hi! I'm not sure if this was intentional or not, but I found a hidden button just under the "Write A Post // Guide Me" buttons (shown in the image below). It routes to the Guide Me URL. So I removed it!
If that button was intentional, then please ignore this PR haha

Screenshot 2023-09-13 at 11 28 53 AM

### CODE REVIEW

**Comment by solomonshalom** [comment]
Hi! @jennifershinshin,

OoO, I didn't actually notice that 🤔 

Let give it a quick look and I will merge it 😄 

P.S. Really appreciate it! It really does help :D <3!

**Review by solomonshalom — COMMENTED** [review]
LGTM!

**Comment by jennifershinshin** [comment]
You're welcome! Yay I got my first official pull request merged! 🥰

**Comment by solomonshalom** [comment]
> You're welcome! Yay I got my first official pull request merged! 🥰

Yay!

**Pull request merged**
