### PR TITLE
Created a search bar that users can use to filter posts by title

### PR DESCRIPTION
**Pull request by jennifershinshin**
# Type of Change
🌱 New feature

# Description

I made a search bar in the Dashboard that allows a user to type in something and searches their posts, filtering by the post title. This search bar will only appear if the user has posts.

# Changes being made
I altered `src/pages/dashboard/index.js` file only.
I made 2 new states:
- `filteredPosts`: Displays the filtered posts
- `searchInput`: Stores the search query that the user types

The `filteredPosts` state's value gets initialized to `posts`.

For the search bar, I set a 500ms delay before filtering the posts to prevent running the search function for every character the user types. This is just a preference and can be changed to having no delay if we want to make that change in the code.
```
useEffect(() => {
  const delayDebounceFn = setTimeout(() => {
    if (posts) filterPosts();
  }, 500)

  return () => clearTimeout(delayDebounceFn)
}, [searchInput])
```

# How has this been tested?

1. Test by searching for posts that have a shared title.
So if the user has 3 posts each named "Post 1", "Post 2", "Post 3" and you type in "post" in the search bar, it should filter out posts to just those 3.
2. Test by creating a new post, naming it "Post 4", and repeating step 1. It should show 4 posts: "Post 1", "Post 2", "Post 3", and "Post 4"
3. Test by updating the title of one of the posts. Then try searching for the title of the updated post. It should pop up in the search query results.
4. Test by typing in a title that none of the posts have. So if you have 3 posts named "Post 1", "Post 2", "Post 3". And you type in "asdf", it should show "No posts matched your search query..."
5. Test by typing something in the search bar. Then delete what you wrote from the search bar. If the search bar is empty, it should show all posts by default.

### CODE REVIEW

**Comment by jennifershinshin** [comment]
Feedback is very much appreciated!
I tried to keep the search bar simple and match with the UI with the rest of the site.
Please let me know if anything needs to be changed and I will work hard to make the necessary changes! ☺️

**Comment by solomonshalom** [comment]
HI! @jennifershinshin,

OoO, LGTM! 😄 

Though, can you style it a little differently? As in, keep the same styles to match the overall aesthetic but I feel there's something missing, am not so sure but I will look into it too!

**Comment by solomonshalom** [comment]
image
A little something like this (Was done via the console so it's not perfect 😅) but again, be as creative as you want - just a small idea from me :D

**Comment by jennifershinshin** [comment]
Ya sure I can style it differently! I'll try with

**Comment by jennifershinshin** [comment]
Accidentally closed PR

**Comment by solomonshalom** [comment]
> Ya sure I can style it differently! I'll try styling it like the screenshot you posted. But ya I agree I do think something is missing.... I think maybe it looks weird because the search bar doesn't usually appear to be in the middle of the page? I'll tinker around with it a bit.
> 
> Also let me know if you think I should change the verbiage for when no results match the search query. I couldn't think of something better than "No posts matched your search query..."
> 
> And that's interesting that it didn't work when you tried filtering with "The". I have a couple questions and things I'd like you to check:
> 
> 1. Is it showing "No posts matched your search query..." when you type in "The"?
> 2. Are you typing "The" in the search bar with capital T or lowercase T?
> 3. Can you check if line 64 in `src/pages/dashboard/index.js` looks like this?
> 
> ```
> let tempPosts = posts.filter(p => p.title.toLowerCase().includes(searchInput.toLowerCase()))
> ```
> 
> I'm wondering maybe the code doesn't have the `toLowerCase()` because I added that in another commit. I'm unable to reproduce the error so I'm trying to understand how you got the error so I can reproduce it.
> 
> Lastly, when you asked me how I think we can implement this so that users can check out user's post, did you mean user's checking out OTHER user's posts? If so, I think we'd have to first think about a couple things before implementing the search function. Things like permissions and having "private posts" and "public posts". Or should all posts be made public?
> 
> If all posts are public, then we'd have to be careful with retrieving every single post in the database every time the user loads the page. An easy way around that is maybe we can just show like 15 most recent posts from other users. And when the user types something in the search bar, we make a call to firestore to get the posts that have the "search query" in the title name. We'd just have to have some sort of table and have pagination so we don't show like 1000 posts in a single page 😅 (Honestly I think there should also be pagination for when you search your own posts cause if a user has a lot of posts, they might have to scroll a lot lol).
> 
> But anyways, definitely a lot to think about! I don't think it'll be difficult, but I'm just trying to figure out what it should look like and how we want it to function.

Hi! @jennifershinshin,

Ahh, I was thinking the same - I guess I hadn't exactly imagined a search bar either so maybe that's why 😅 but on the verbiage, sure! will work on it 😄 

Sure, I checked and these the test results:

1. Nope, but when I typed in something different (Ex: `Lol`) it would show up the text
2. Tried both, didn't work 🤔 
3. Found it, seems to be good!

I was thinking it would be rather cool on if we can implement a search that could allow the users to retrieve posts that have been made public and Yes! it would be weird if we get a thousand posts being shown 😅 

ALSO, please do know if you need any help - please don't hesitate to ask and I too, will be looking into it as well!

P.S. Really Appreciate it! :D

**Comment by jennifershinshin** [comment]
I see... What exactly did it show when you typed in "The"? Could you send a screenshot by any chance?
And I appreciate the offer for help! If I'm still stuck on the search bar bug, I'll definitely reach out to you for help 😊

And for the feature to search for public posts, it does sounds like a cool thing to add. I can try to create a working version of it on my branch and show it to you once I'm done for any feedback and adjustments.
Would the "global search" have its own separate page aside from "Dashboard"? Like an "Explore" page? Or would that "global search" be on the Dashboard?

**Comment by solomonshalom** [comment]
> I see... What exactly did it show when you typed in "The"? Could you send a screenshot by any chance? And I appreciate the offer for help! If I'm still stuck on the search bar bug, I'll definitely reach out to you for help 😊
> 
> And for the feature to search for public posts, it does sounds like a cool thing to add. I can try to create a working version of it on my branch and show it to you once I'm done for any feedback and adjustments. Would the "global search" have its own separate page aside from "Dashboard"? Like an "Explore" page? Or would that "global search" be on the Dashboard?

Hi! @jennifershinshin 

Okay, I couldn't believe my eyes but I realized that when I searched "The" in the search bar, I only had three posts and guess what they all had in common? "The" 😭 

So, technically it searched up the posts and to further test it out, I wrote a post under the title "C" and when I searched again, it showed me the original three posts. So, I don't think there was a problem w/ the code, it was just me :,)

On the thought of adding a search bar universally, we could remove the `contact` button and replace it w/ explore - that would be cool because adding too many buttons wouldn't be responsive on all devices and will look cluttered. Let's not add it to the dashboard, just so that we don't confuse the users but if you have another better idea, do that! I don't want to be the one to stop you from going w/ it 😅

P.S. I am so sorry! I should've noticed and I didn't, am so sorry for the inconvenience!

**Comment by solomonshalom** [comment]
> LOL it's ok it happens 😂 At least we know it wasn't a complex bug. And it also helped me find another bug that I fixed so that's good.
> 
> And I appreciate your feedback for the universal search bar. I'll start working on that and also try to play around with the UI for the search bar in the dashboard.

Ah, loll but glad you found a bug // fixed it 😓 

Alright! Super Excited - Thanks @jennifershinshin 😄

**Comment by solomonshalom** [comment]
Hi @jennifershinshin,

Just saw the commit, it looks so good! :D

Though, super curious but why did you change the positions of the `Write A Post` & `Guide Me` buttons? It does look pretty cool but was super curious 🤔 

OH, ALSO - Don't have a good day, have a great day! (It's 12AM here so 😅 )

**Comment by jennifershinshin** [comment]
Oh shoot I didn't realize my commits would show on this PR LOL.
It's still a work in progress 😅 I finished creating the Search component but the I was in the middle of working on the UI and stopped so it's not final lol.
I changed the positions of Write a Post and Guide Me because I wanted the Search bar to be next to the Write a Post button (since they're both "post" related). But again, I might change it around. Still experimenting haha

**Comment by solomonshalom** [comment]
> Oh shoot I didn't realize my commits would show on this PR LOL. It's still a work in progress 😅 I finished creating the Search component but the I was in the middle of working on the UI and stopped so it's not final lol. I changed the positions of Write a Post and Guide Me because I wanted the Search bar to be next to the Write a Post button (since they're both "post" related). But again, I might change it around. Still experimenting haha

OH, DW About it! It looks pretty good, honestly! 

Though, pretty good idea to keep them in one place, that's a good thought 😮 

Super excited to check out the final results :D

**Comment by jennifershinshin** [comment]
Hi! I just pushed a commit with the updated UI. I know it's a little different, so feel free to give honest feedback and any changes you want made.
I only changed the UI for when users have posts already.
I put the "Guide me" button at the bottom right and made it appear as a simple question mark, since I've seen that commonly in some websites. I did this because I imagined for a user that's already familiar with The Abyss, they wouldn't need to see the Guide Me button all the time. And also I just couldn't find a good place to put it lol. 
I kept your original UI for when users don't have any posts, in case you still wanted the original UI.

**Comment by solomonshalom** [comment]
PSS, what do you think of [Iconoir](https://iconoir.com/) as the icon-set for the entire project? It looks pretty cool and I really love the attention to detail but should we go w/ it? 🤔

**Comment by jennifershinshin** [comment]
Thanks!

I used react-icons only because it was the first result to pop up when I was searching for icons to use lol. I think Iconoir looks great. I just implemented it in my newest commit. I changed the icons to use Iconoir icons and I used the pencil icon like you suggested.

Also, great question about what I would do if I removed the original UI. To be honest, I'm not sure what I would change about it haha. I think I would get rid of the double slash '//' in between the Write a Post and the Guide Me button because it doesn't serve much purpose. And maybe I would try to add a little more info on that page. Something like
```
Welcome to the Abyss! 🔥 A Beautiful Place to Free your Mind ✨

Write a Post to get started! -> [📝 Write a Post button]

Explore other people's writings! -> [🌎 Explore button]

Or get some ideas here! -> [🙋 Guide me button]
```
Of course it's not perfect, but that's the general direction I'd go for if I were to change the original UI.

If there's any other changes you can think of, please let me know! Otherwise, if everything looks good, I will merge it 😁
But I'll probably wait until October 1 to merge it to get that Hacktoberfest credit XD

**Comment by solomonshalom** [comment]
> Thanks!
> 
> I used react-icons only because it was the first result to pop up when I was searching for icons to use lol. I think Iconoir looks great. I just implemented it in my newest commit. I changed the icons to use Iconoir icons and I used the pencil icon like you suggested.
> 
> Also, great question about what I would do if I removed the original UI. To be honest, I'm not sure what I would change about it haha. I think I would get rid of the double slash '//' in between the Write a Post and the Guide Me button because it doesn't serve much purpose. And maybe I would try to add a little more info on that page. Something like
> 
> ```
> Welcome to the Abyss! 🔥 A Beautiful Place to Free your Mind ✨
> 
> Write a Post to get started! -> [📝 Write a Post button]
> 
> Explore other people's writings! -> [🌎 Explore button]
> 
> Or get some ideas here! -> [🙋 Guide me button]
> ```
> 
> Of course it's not perfect, but that's the general direction I'd go for if I were to change the original UI.
> 
> If there's any other changes you can think of, please let me know! Otherwise, if everything looks good, I will merge it 😁 But I'll probably wait until October 1 to merge it to get that Hacktoberfest credit XD

Hi! @jennifershinshin 

Ah, loll (I remember clicking the very first link that Google recommended so can relate 😆). ALSO, thanks for implementing `Iconoir Icons`, it looks awesome! 😄

Honestly, the design (Including the one you prototyped 😁) for when new and old users will see in their dashboard looks pretty good and I think that it will really help a lot of people (Trust me when I say that A LOT of people didn't even know what to do when they logged-in 😭) but Yes! let's wait till October and smash that merge! Super excited :D

P.S. Super curious but how are you planning on implementing the search globally? You did tell me but I wanted to really understand the technical-side of it 🤔 ONE MORE THING, don't have a good day - have a great day! (It's 4AM here so :D)

**Comment by jennifershinshin** [comment]
I just pushed a commit with the UI I prototyped for when users have no posts. I'm not sure what I think about it, but take a look and let me know if you want to keep it or revert it lol
(Obviously I left out the explore button because it's not yet implemented.)

For the global search implementation it's really simple. I was just going to have a new page dedicated to the Explore page. Then I'd retrieve only published posts from firestore. And only get like the first 15 or 20 posts, and orderBy 'lastEdited'.
```
const [explorePosts, explorePostsLoading, explorePostsError] = useCollectionData(
  firestore.collection('posts')
  .where('published', '==', true)
  .orderBy('lastEdited')
  .limit(15)
)
```
Then I'd add another `where` to the query for the search query. So if a user searches for posts with "The" in the title, you'd do something like "where title contains 'The'"
I did a little bit of research and I think you have to use something like this:
```
Firestore.instance
 .collection('Col-Name')
 .where('fieldName', isGreaterThanOrEqualTo: searchKey)
 .where('fieldName', isLessThan: searchKey +’z’)
```
I learned about it here:
- https://medium.com/feedflood/filter-by-search-keyword-in-cloud-firestore-query-638377bf0123
- https://stackoverflow.com/questions/68578591/how-to-search-in-firestore-database

I don't completely understand the `isGreaterThanOrEqualTo` and `isLessThan` that they're speaking of but I'm gonna experiment with it.

If you see any problems in my logic, please let me know!

**Comment by solomonshalom** [comment]
> I just pushed a commit with the UI I prototyped for when users have no posts. I'm not sure what I think about it, but take a look and let me know if you want to keep it or revert it lol (Obviously I left out the explore button because it's not yet implemented.)
> 
> For the global search implementation it's really simple. I was just going to have a new page dedicated to the Explore page. Then I'd retrieve only published posts from firestore. And only get like the first 15 or 20 posts, and orderBy 'lastEdited'.
> 
> ```
> const [explorePosts, explorePostsLoading, explorePostsError] = useCollectionData(
>   firestore.collection('posts')
>   .where('published', '==', true)
>   .orderBy('lastEdited')
>   .limit(15)
> )
> ```
> 
> Then I'd add another `where` to the query for the search query. So if a user searches for posts with "The" in the title, you'd do something like "where title contains 'The'" I did a little bit of research and I think you have to use something like this:
> 
> ```
> Firestore.instance
>  .collection('Col-Name')
>  .where('fieldName', isGreaterThanOrEqualTo: searchKey)
>  .where('fieldName', isLessThan: searchKey +’z’)
> ```
> 
> I learned about it here:
> 
> * https://medium.com/feedflood/filter-by-search-keyword-in-cloud-firestore-query-638377bf0123
> * https://stackoverflow.com/questions/68578591/how-to-search-in-firestore-database
> 
> I don't completely understand the `isGreaterThanOrEqualTo` and `isLessThan` that they're speaking of but I'm gonna experiment with it.
> 
> If you see any problems in my logic, please let me know!

Shalom! @jennifershinshin,

I just checked out the commit and although it does help in guiding people, I feel it's better if we revert to the original design w/ a small change - which is that you can add the emojis (📝 for `Write A Post` & 🙋 for `Guide Me`) that you had implemented. 

OH, I also wanted to mention that when you revert to the original design - keep the `left` property of the `//` style to `10.5em` to keep it in-between the two elements (See below on how I did it).  

image

Regarding your implementation of the global search, I really can't comment as it's not someting I've exactly experimented 😅 but try it out! It seems pretty good and I am sure it will work out 😄

ALSO, a lot of people have published their posts w/o any text whatsoever in the article and if anyone were to click on it, it would just state that it's `untitled` -
image

Is it possible to implement a `if & else statement` (I am not so sure on how it would work out but I will see what I can do 🤔 ) that could only show posts that has text in it, specifically the title and the main text. This way, we can show the people - actual written posts (I should've implemented a function to check wheter or not those areas were written 😬).

Though, I love the progress and super excited to see it come to life! BTW, when do you think you would be able to implement this? (No need to hurry, just super excited 👾)

God Bless!

**Comment by jennifershinshin** [comment]
Hi!
Sure! I reverted to the original UI, added the emojis, and kept the left property of the // style to 10.5em.
I think it looks good! I will push merge this pull request on October 1 if everything looks good.

And yes, I can do that if/else statement for the global search. That's a good idea.

For implementing the global search, I can get it done maybe within a week. The longest part will be the UI because I'm not very good at css lol. And I want it to look good. Btw, let me know if you have any suggestions for how the global search should look like! I was thinking we could display a bunch of cards representing the posts. And we'd show the cards in rows, each row would have 3 cards.

Like this:
[card] [card] [card]
[card] [card] [card]
[card] [card] [card]
etc...

This is the card design I was going for -> https://dribbble.com/shots/18941937-Simple-Card-Ui

**Comment by solomonshalom** [comment]
> Hi! Sure! I reverted to the original UI, added the emojis, and kept the left property of the // style to 10.5em. I also synced my fork, thanks for reminding me! I think it looks good! I will push merge this pull request on October 1 if everything looks good.
> 
> And yes, I can do that if/else statement for the global search. That's a good idea.
> 
> For implementing the global search, I can get it done maybe within a week. The longest part will be the UI because I'm not very good at css lol. And I want it to look good. Btw, let me know if you have any suggestions for how the global search should look like! I was thinking we could display a bunch of cards representing the posts. And we'd show the cards in rows, each row would have 3 cards.
> 
> Like this: [card] [card] [card] [card] [card] [card] [card] [card] [card] etc...
> 
> This is the card design I was going for -> https://dribbble.com/shots/18941937-Simple-Card-Ui

Shalom! @jennifershinshin,

It looks great! thanks for syncing the fork too 😄 

ALSO, about the design, why don't you use the CSS of the reading list? It looks like this - 
image

That way you don't have to stress a lot on the CSS (Not that I don't like the dribble design but that it would be quite hard to implement a new design altogether) and you can easily implement it too! :D

**Comment by jennifershinshin** [comment]
Ya that looks great! I'll use that design. Thanks :)

**Comment by solomonshalom** [comment]
> Ya that looks great! I'll use that design. Thanks :)

Shalom! @jennifershinshin,

Perfect! Looking forward to it :D

**Comment by jennifershinshin** [comment]
Can you review the PR? I think I need 1 approving review to merge it.

**Review by solomonshalom — APPROVED** [review]
Shalom! @jennifershinshin,

LGTM! 😄 Thank you so much for taking your time and working on this, it really means a lot to us! 

Arigato Gozaimasu!

**Comment by solomonshalom** [comment]
BTW, there seems to be a bug but if you aren't able to merge the PR, let me know and I will do it :D

**Comment by jennifershinshin** [comment]
Ya it says merging is blocked because it's missing a successful Production deployment. I think it might be related to the branch settings according to this post https://github.com/orgs/vercel/discussions/3215
But I'm not sure.
If you're able to merge the PR, feel free to do so! Because it seems like I'm not able to 😅

**Comment by solomonshalom** [comment]
> Ya it says merging is blocked because it's missing a successful Production deployment. I think it might be related to the branch settings according to this post https://github.com/orgs/vercel/discussions/3215 But I'm not sure. If you're able to merge the PR, feel free to do so! Because it seems like I'm not able to 😅

Shalom! @jennifershinshin,

I just checked out the issue you mentioned and fixed it! go ahead and merge it - not that I don't want to do it but you deserve it! 😁

**Comment by jennifershinshin** [comment]
Thanks for fixing it! And I appreciate you for wanting me to merge it but it shows that only those with write access can merge PRs. I think you should merge it! 😁
Screenshot 2023-10-02 at 12 05 17 PM

**Comment by solomonshalom** [comment]
> Thanks for fixing it! And I appreciate you for wanting me to merge it but it shows that only those with write access can merge PRs. I think you should merge it! 😁 Screenshot 2023-10-02 at 12 05 17 PM

Shalom! @jennifershinshin,

OH-

I might have not configured the branch right, I apologize but I will give it a merge 😓 

Though, this whole journey has been really fun and I really did learn a lot too! thank youu (I know it takes a lot of time // effort to do really brainstrom and implement a new feature, really apprecaite it)! Super excited to show this to my team too!! :D

P.S. ALSO, don't just have a good day - have a great day!

**Comment by jennifershinshin** [comment]
@solomonshalom Btw do you know how to I'm able to get progress for hacktoberfest? My hacktoberfest profile still shows 0/4 in progress even after this PR got merged 😭 If not it's ok, I'm not really doing open source for hacktoberfest.

**Comment by solomonshalom** [comment]
> @solomonshalom Btw do you know how to I'm able to get progress for hacktoberfest? My hacktoberfest profile still shows 0/4 in progress even after this PR got merged 😭 If not it's ok, I'm not really doing open source for hacktoberfest.

OH, I had the same problem but after some time it was resolved 🤔 (Trust me, I was literally in your same shoes - I made 4PRs and nothing showed up for a few minutes, you could tell that I was FREAKING out 😭)

But try making a PR again on The Abyss and I will give it a merge, see if that will be added to the progress of hacktoberfest?

**Pull request merged**
