### PR TITLE
Hello! Mom

### PR DESCRIPTION
**Pull request by jennifershinshin**
### Type of Change
✨ Enhancement

### Description
- Updated tabs in header to be consistent throughout all pages.
- Highlighted the current tab you're on
- Removed the 'Contact' tab

### Changes being made
- Changes to the HTML for the dashboard and reading list files to highlight the current tab you're on and also remove the contact tab

### How was this tested?
- Click the Dashboard tab and it should route you to the Dashboard page and the Dashboard tab should be highlighted
- You should expect the same behavior for the Reading List tab

### CODE REVIEW

**Review by solomonshalom — APPROVED** [review]
LGTM 😄 

Could you also add your contributions to the `AUTHORS.md` as well? Other than that, looks pretty good! Thanks @jennifershinshin :D

**Comment by solomonshalom** [comment]
Shalom! @jennifershinshin,

Just checked it out and while everything seems good, the responsiveness could be a little better - do you think a burger menu should do it or maybe a little CSS spacing? I am not sure but I think if we fix that, it will be perfect ✨

**Comment by jennifershinshin** [comment]
Ah I see! Is it like slow?
I'll see what I can do

**Comment by jennifershinshin** [comment]
@solomonshalom I'm having trouble understanding what you mean by its responsiveness. I tried having 4+ tabs, and it seems responsive. Can you elaborate?

**Comment by solomonshalom** [comment]
> @solomonshalom I'm having trouble understanding what you mean by its responsiveness. I tried having 4+ tabs, and it seems responsive. Can you elaborate?

Sure! What I meant to say is if it would look cluttered if we were to have more than 4+ tabs and so if it did look cluttered, could we fix it by using a command bar (Ex. [CMDK](https://cmdk.paco.me/), [KBar](https://kbar.vercel.app/), or [Kmenu](https://kmenu.hxrsh.in/)) 🤔 

P.S. I am so sorry for the inconvenience! 😓

**Comment by jennifershinshin** [comment]
Ah I see. I feel like command bar would be useful if we have like a ton of tabs, but if we're expecting just 5-6ish tabs.
What do you think of this idea? We can consolidate the Profile and Signout button into a small dropdown menu like [this](https://dribbble.com/shots/22709920-Dropdown-menu) or [this](https://dribbble.com/shots/2623344-Dropdown-Menu?utm_source=Clipboard_Shot&utm_campaign=pedrocanelas&utm_content=Dropdown%20Menu&utm_medium=Social_Share&utm_source=Clipboard_Shot&utm_campaign=pedrocanelas&utm_content=Dropdown%20Menu&utm_medium=Social_Share) and display the user's profile picture just like in those designs.

So it would look like this:
`Dashboard        Reading List           [Profile Picture drowndown menu]`

**Comment by solomonshalom** [comment]
> Ah I see. I feel like command bar would be useful if we have like a ton of tabs, but since we're expecting 5-6 tabs, I don't think it's useful. What do you think of this idea? We can consolidate the Profile and Signout button into a small dropdown menu like [this](https://dribbble.com/shots/22709920-Dropdown-menu) or [this](https://dribbble.com/shots/2623344-Dropdown-Menu?utm_source=Clipboard_Shot&utm_campaign=pedrocanelas&utm_content=Dropdown%20Menu&utm_medium=Social_Share&utm_source=Clipboard_Shot&utm_campaign=pedrocanelas&utm_content=Dropdown%20Menu&utm_medium=Social_Share) and display the user's profile picture just like in those designs.
> 
> So it would look like this: `Dashboard Reading List [Profile Picture drowndown menu]`
> 
> Also do you think this hamburger menu should be a separate issue? I think we can just merge this PR if you think everything looks good, and create a new issue for the hamburger menu if you like the idea of the hamburger menu.

Shalom! @jennifershinshin,

OoO, I checked the design and they look really cool! I like this [one](https://dribbble.com/shots/22709920-Dropdown-menu) better, mainly because it really matches the vibe // aesthetics of The Abyss 😁 

P.S. The command-bar was, to me, more of a future-proof design - mainly because if we have more hyperlinks or tabs to add, we could do it through the command-bar but then again, I do like both designs (I am a tad bit biased for the command-bar but I would be lying if I told that the drop-down does not look 🔥) and what you think is the best - implement that!

Edit: What if we add the user's PFP, and when the user clicks on the PFP - it would show up in the command-bar? (Small idea BUT what you think is best - implement that!)

**Comment by solomonshalom** [comment]
> Ah I see. I feel like command bar would be useful if we have like a ton of tabs, but since we're expecting 5-6 tabs, I don't think it's useful. What do you think of this idea? We can consolidate the Profile and Signout button into a small dropdown menu like [this](https://dribbble.com/shots/22709920-Dropdown-menu) or [this](https://dribbble.com/shots/2623344-Dropdown-Menu?utm_source=Clipboard_Shot&utm_campaign=pedrocanelas&utm_content=Dropdown%20Menu&utm_medium=Social_Share&utm_source=Clipboard_Shot&utm_campaign=pedrocanelas&utm_content=Dropdown%20Menu&utm_medium=Social_Share) and display the user's profile picture just like in those designs.
> 
> So it would look like this: `Dashboard Reading List [Profile Picture drowndown menu]`
> 
> Also do you think this hamburger menu should be a separate issue? I think we can just merge this PR if you think everything looks good, and create a new issue for the hamburger menu if you like the idea of the hamburger menu.

Also, regarding the hamburger menu, I doubt if a separate issue is needed but I could first merge this PR of yours and then you could open another - If that works for you 😄

**Comment by jennifershinshin** [comment]
Ok I understand!
If you want to use the hamburger menu or the command-bar, I think it's best to just close this PR without merging. I probably moved too fast on the new UI design and made a PR without your input, oops! 😅

In the meantime, I'll look for any bugs that need fixing or backend work, since I'm more interested in backend stuff.

**Comment by solomonshalom** [comment]
> Ok I understand! If you want to use the hamburger menu or the command-bar, I think it's best to just close this PR without merging. I probably moved too fast on the new UI design and made a PR without your input, oops! 😅
> 
> In the meantime, I'll look for any bugs that need fixing or backend work, since I'm more interested in backend stuff.

OH, that's completely alright! I would have actually merged this PR so it would count towards your hacktoberfest participation and when you did implement the PFP-menu or Kbar, I would have merged that too 😅

**Pull request closed without merging**
